version: '2'
services:
    web:
        build: .
        ports:
            - "80:80"
        volumes:
            - .:/code
        depends_on:
            - mongodb
    mongodb:
        image: mongo
