apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: crudapp
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crudapp
spec:
  selector:
    matchLabels:
      app: crudapp
  replicas: 2
  template:
    metadata:
      labels:
        app: crudapp
    spec:
      containers:
      - name: crudapp
        image: mycrudapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000